version: 0.0
os: linux
files:
  - source: ./dist/package.json
    destination: /home/ec2-user/jourdetrade
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_node_modules.sh
      runas: root
  ApplicationStart:
    - location: scripts/launch_jourdetrade.sh
      timeout: 300
      runas: root
